print("january")
print
("february")
print("march")
print("april")
print("may")
print("june")
print("july")
print("august")
print("september")
print("october")
print("november")
print("december")
print("the total number of months in a year is 12")
print("the total number of days in a year is 365")
print("the total number of weeks in a year is 52")
print("the total number of days in a month is 30 or 31")
print("the total number of days in february is 28 or 29")
print("the total number of weeks in a month is 4")
